/**
 * author: Martin
 * define constants using in this project
 */

var Constant	= {
		SERVER_ERR				: 'SERVER_ERR',
		QUERY_ERR 				: 'QUERY_ERR',
		EMPTY_DATA 				: 'EMPTY_DATA',
		FAILED_CODE				: 'FAILED',
		FAILED_LOG				: 'FAILED_LOG',
        EXISTED				    : 'EXISTED',
        NOT_EXISTED				: 'NOT_EXISTED',
        CONNECTED				: 'CONNECTED',
        CANNOT_CONNECTED		: 'CANNOT_CONNECTED',
		OK_CODE					: 'OK',
		LOGINED					: 'LOGINED',
		MISMATCH_PARAMS			: 'MISMATCH_PARAMS',    //wrong/missing parameters sending to server
        MALFORMED_PARAM         :   'MALFORMED_PARAM',  //param is not correct format
        NOT_FOUND               : 'NOT_FOUND',
		INVALID_PARAM_VALUE     :   'INVALID_PARAM_VALUE',
		SYSTEM_OWNER_NOT_FOUND  :   'SYSTEM_OWNER_NOT_FOUND',
        GROUP_OWNER_NOT_FOUND  :   'GROUP_OWNER_NOT_FOUND',
        SYSTEM_ADDRESS_NOT_FOUND   :   'SYSTEM_ADDRESS_NOT_FOUND',  //cannot connect to system db
        SYSTEM_NOT_FOUND          :   'SYSTEM_NOT_FOUND',
        USER_NOT_FOUND          :   'USER_NOT_FOUND',
        GROUP_NOT_FOUND          :   'GROUP_NOT_FOUND',
        UNAUTHORIZATION          :   'UNAUTHORIZATION',
        RECORD_NOT_FOUND         : 'RECORD_NOT_FOUND',
        COMMENT_NOT_FOUND         : 'COMMENT_NOT_FOUND',
		INVALID_REQUEST         :   'INVALID_REQUEST',
		COMMON_KEY_NOT_FOUND    : 'COMMON_KEY_NOT_FOUND',       //common key not found in Group or System
		CREATE_NOTIF_FAIL      :   'CREATE_NOTIF_FAIL',    //create notification is failed
		DUPLICATE_CODE:		'DUPLICATE_CODE',
    	DUPLICATE_MAGNET_LINK:		'DUPLICATE_MAGNET_LINK',


		UTF_8					: 'UTF-8',
		TRUE					: true,
		FALSE					: false,
		STR_TRUE				: 'true',
		STR_FALSE				: 'false',
		INCREASE_1_FACTOR       :  1,   //used to increase counting number
        DECREASE_1_FACTOR       :  -1,
        PREVIOUS_RELATED_ITEMS_LEN: 5,  //such as: get 5 latest persons who commented
		UNDERSCORE: '_',
		COMMA: ',',
		DOT: '.',
		YES_NUMBER_VAL: 1,		//replace for "true" value because number is easier to compare
		STR_ALL: 'all',
		STR_YES: 'yes',
		STR_NO: 'no',
		LINE_FEED_CHAR: '\r\n',
		DEFAULT_PAGE_LENGTH: 50,        //number of items in 1 paging
        SEARCH_TYPE_AND:    'AND',
        SEARCH_TYPE_OR:     'OR',
        CAST_ERROR: 'CastError',        //message from query mongodb
        ObjectID: 'ObjectID',
        ObjectId: 'ObjectId',
        MAX_TOKEN_NUM:  999,    //number of tokens that can send via Firebase
		PARAM: {	//params of APIs sent from client app
            _ID: '_id',
            NAME: 'name',
            USER_ID: 'user_id',
            USER_NAME: 'user_name',
			EMAIL: 'email',
		},
    	SALT_ENCRYPTION : 'cfIrAsuGLONFivnz0axTDAISIuJ4vQc7yF2yE393j1k=',    //generated by Fernet.generate_key() in Python
		SESSION: {
            KEY_USER_ID: 'KEY_USER_ID'	//username
		},
		INVALID_DEVICE_PREFIX: 'INVALID_DEVICE_PREFIX_'
};
//
module.exports = Constant;
